apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-preview-set
spec:
  generators:
    - pullRequest:
        github:
          owner: exampledotcom
          repo: example-app
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'example-app-{{ branch }}-{{ number }}'
    spec:
      destination:
        namespace: 'preview-{{ branch }}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: charts/
        repoURL: 'https://github.com/exampledotcom/example-config.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{ branch }}'
            # see .env.IMAGE_NAME_TAG in example-app/.github/workflows/build-container.yaml
            - name: imagename
              value: example-app
            # to match ${{ github.ref_name }}-${{ github.sha }}
            - name: imagetag
              value: '{{ branch }}-{{ head_sha }}'
            - name: name
              value: example-app
            - name: ingressport
              value: '9090'
      syncPolicy:
        automated:
          selfHeal: true