apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-preview-set
spec:
  generators:
    - scmProvider:
        github:
          organization: 'Cofinity-X'
          allBranches: true
          tokenRef:
            key: token
            secretName: github-token
        cloneProtocol: "https"
        requeueAfterSeconds: 30
        filters:
          - repositoryMatch: '^example-app'
            branchMatch: '^feat'
          - repositoryMatch: '^cofinity-x'
            branchMatch: '^dev'
            pathsExist: [k8s/kustomization.yaml]
            pathsDoNotExist: [argo.disable]
  template:
    metadata:
      name: '{{ repository }}-{{ branchNormalized }}'
    spec:
      destination:
        namespace: dev-previews
        server: https://kubernetes.default.svc
      project: default
      source:
        path: 'charts/'
        repoURL: 'https://github.com/exampledotcom/example-config.git'
        targetRevision: 'HEAD'
        helm:
          parameters:
            - name: name
              value: '{{ repository }}-{{ branch }}'
            - name: imagename
              # see .env.IMAGE_NAME_TAG in example-app/.github/workflows/build-container.yaml
              value: '{{ repository }}'
            - name: imagetag
              # to match ${{ github.ref_name }}-${{ github.sha }}
              value: '{{ branch }}-{{ sha }}'
            - name: url
              value: '{{ branch }}.pre'
            # - name: 'ingress.host'
            #   value: 'dev-{{ branchNormalized }}.dev.cofinity-x.com'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true
