apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-preview-set
spec:
  generators:
    - scmProvider:
        github:
          organization: exampledotcom
          allBranches: true
          tokenRef:
            key: token
            secretName: github-token
        cloneProtocol: "https"
        filters:
          - repositoryMatch: '^example-app'
            branchMatch: '^feat'
        values:
          registry: 'docker.io'
  template:
    metadata:
      name: '{{ repository }}-{{ branchNormalized | replace "." "-" }}'
    spec:
      destination:
        namespace: dev-previews
        server: https://kubernetes.default.svc
      project: default
      source:
        path: 'charts/'
        repoURL: '{{ url }}'
        targetRevision: '{{ branch }}'
        helm:
          parameters:
            - name: name
              value: '{{ repository }}'
            # see .env.IMAGE_NAME_TAG in example-app/.github/workflows/build-container.yaml
            - name: imagename
              value: '{{ repository }}'
            # to match ${{ github.ref_name }}-${{ github.sha }}
            - name: imagetag
              value: '{{ branch }}-{{ head_sha }}'
            - name: url
              value: 'dev-{{ branch }}'
            - name: ingressport
              value: '9090'
            # - name: 'ingress.host'
            #   value: 'preview-{{ branchNormalized | replace "." "-" }}.dev.exampledotcom.io'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true
